spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: sa
    password: 123    
# logging
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: debug

